[{
    "user_name":"abi",
    "date":ISODate("2020-10-16"),
    "attendance":"absent",
    "task_submission":"failed"
},
{
    "user_name":"alice",
    "date":ISODate("2020-10-20"),
    "attendance":"absent",
    "task_submission":"failed"
},
{
    "user_name":"bernard",
    "date":ISODate("2020-10-29"),
    "attendance":"present",
    "task_submission":"passes"
},
{
    "user_name":"ronnie",
    "date":ISODate("2020-11-01"),
    "attendance":"absent",
    "task_submission":"passed"
},
{
    "user_name":"roshan",
    "date":ISODate("2020-11-16"),
    "attendance":"present",
    "task_submission":"failed"
},
{
    "user_name":"tony",
    "date":ISODate("2020-11-17"),
    "attendance":"present",
    "task_submission":"passed"
}]